#!/bin/bash

# Check if a c file is provided as a parameter
if [ -z "$1" ]; then
    echo -e "\e[31mUsage: $0 <c_program_file.c>\e[0m"
    exit 1
fi

# Get the filename and extension
file="$1"
filename=$(basename -- "$file")
extension="${filename##*.}"

# Check if the file has a .c extension
if [ "$extension" != "c" ]; then
    echo -e "\e[31mError: Please provide a C (.c) file\e[0m"
    exit 1
fi

# Compile the Rust program
g++ "$file" --output "crun_output_file"

# Check if compilation was successful
if [ $? -eq 0 ]; then
    echo -e "\e[32mCompilation successful. Running the program:\e[0m"
    echo -e "\e[34mOutput:\e[0m"

    # Run the compiled program
    ./crun_output_file

    # Uncomment the following line if you want to display the content of the C file
    # echo -e "\nContent of $file:"
    # cat "$file"

    # Delete the compiled executable file
    rm -rf crun_output_file
else
    echo -e "\e[31mCompilation failed.\e[0m"
fi

